### ISSUE TITLE
Govee RGBW 

### ISSUE THREAD

**Issue by mbhforum** [LaggAt/hacs-govee#151]
## Version of the custom_component

Using 
2023.11.1 from HACS

## Configuration

```yaml

Add your logs here.

An example of me trying to set the color up in a Script and showing the error in the log.

Logger: homeassistant.components.script.kitchen_cabinet_lights_on
Source: helpers/script.py:1792
Integration: Script ([documentation](https://www.home-assistant.io/integrations/script), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+script%22))
First occurred: 12:49:11 PM (7 occurrences)
Last logged: 12:51:17 PM

Kitchen Cabinet Lights On: Error executing script. Invalid data for call_service at pos 1: expected tuple for dictionary value @ data['rgbw_color']
Kitchen Cabinet Lights On: Error executing script. Invalid data for call_service at pos 1: None for dictionary value @ data['rgbw_color']
Kitchen Cabinet Lights On: Error executing script. Invalid data for call_service at pos 1: two or more values in the same group of exclusion 'Color descriptors' @ data[<Color descriptors>]
```

## Describe the bug

I am trying to setup scripts or scenes to automate turning on Govee Spot Lighting (H7065) and Strip Lighting (H6159) and while I can turn the lights on/off, changing the color to a White/Soft White  color and temperature of them through Scripts or in the HA GUI does not seem to work.  I click on a White Color in the GUI and nothing happens. I am forced to configure the color settings in the Govee app.  

## Debug log

```text

Add your logs here.

```
