### ISSUE TITLE
Setting of brightness and colors laggy and unrealiable

### ISSUE THREAD

**Issue by jclsn** [LaggAt/hacs-govee#69]
## Version of the custom_component

0.22

## Configuration
```

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem
    
influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: influx_user
  password: xxxxxxxxxxxxxxxxxxxx
  ssl: false
  verify_ssl: false
  max_retries: 3
  default_measurement: state
      
sensor:
    - platform: openweathermap_all
      api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      longitude: 10.0385239
      latitude: 53.5734864

emulated_hue:
  host_ip: 192.168.184.71
  listen_port: 8300
  advertise_ip: 10.0.0.10
  advertise_port: 8080
  expose_by_default: true
  
python_script:
```
I only configured refresh rate to 1 and set the API key.

## Describe the bug
When rapidly changing colors, the response is very laggy. Sometimes the cursor also moves around uncontrollably on the the color wheel. It seems to get worse, the more colors you tap in a short period of time. Like the events are being buffered and worked off too slowly.

## Debug log

https://pastebin.com/5C8WS4XE
